code review
Mutalenic/TodoListpeerReview pull request #1
Opened 2022-03-07 14:01 UTC by Mutalenic

This is a peer to peer code review.

2022-03-07 15:13 UTC, Mehdi-Rh requested changes

2022-03-07 15:13 UTC, Mehdi-Rh commented on src/controllTools.js
> +import { checkbox, editTask } from './index.js';
Great job so far, in my opinion there is still something that needs improvement, , you can see the video below:
https://www.loom.com/share/4a456d42e49340c0b24085b944874b2d

2022-03-08 15:02 UTC, Mehdi-Rh approved these changes
Great job, the requested changes were perfectly implemented !!

2022-03-08 16:46 UTC, Mutalenic commented
> Great job, the requested changes were perfectly implemented !!

Thanks, the review was professionally done

2022-03-08 16:46 UTC, merged